#!/usr/bin/env bash
# install.sh — Runner-Ops Squad
# Prepares a repo to use the runner-ops pack without making runners depend on it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SQUAD_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$SQUAD_DIR/../.." && pwd)"
RUNNER_LIB_DIR="$REPO_ROOT/infrastructure/scripts/runner-lib"
REGISTRY_FILE="$RUNNER_LIB_DIR/runner-registry.yaml"

show_help() {
  cat <<EOF
install.sh — Validate and prepare runner-ops installation

Usage:
  $(basename "$0")            Validate install + create local outputs dirs
  $(basename "$0") --doctor   Validate only

This script does not copy runner-lib into squads/runner-ops.
It enforces the boundary:
  - runner-ops pack is self-contained for installation
  - runners generated by it must depend only on infrastructure/scripts/runner-lib/
EOF
}

DOCTOR_ONLY="false"

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --doctor) DOCTOR_ONLY="true"; shift ;;
      --help|-h) show_help; exit 0 ;;
      *) echo "Unknown flag: $1" >&2; show_help; exit 1 ;;
    esac
  done
}

check_file() {
  local path="$1"
  [[ -e "$path" ]] || {
    echo "ERROR: missing required asset: $path" >&2
    exit 1
  }
}

main() {
  parse_args "$@"

  check_file "$RUNNER_LIB_DIR/pipeline-bootstrap.sh"
  check_file "$RUNNER_LIB_DIR/validate-runner.sh"
  check_file "$REGISTRY_FILE"
  check_file "$SQUAD_DIR/config.yaml"
  check_file "$SQUAD_DIR/tasks/create-runner.md"

  if [[ "$DOCTOR_ONLY" != "true" ]]; then
    mkdir -p "$REPO_ROOT/outputs/runner-ops/validation"
    mkdir -p "$REPO_ROOT/outputs/runner-ops/health"
    chmod +x "$SQUAD_DIR"/scripts/*.sh
  fi

  echo "runner-ops install OK"
  echo "Canonical runner-lib: $RUNNER_LIB_DIR"
  echo "Canonical registry:   $REGISTRY_FILE"
  echo "Boundary: runners must not depend on $SQUAD_DIR"
}

main "$@"
